# Generated by Django 3.2.5 on 2021-09-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='user',
            name='latname',
            field=models.CharField(default='LastName', max_length=50),
        ),
    ]
