# Generated by Django 3.2.5 on 2021-09-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(default='Computer Science', max_length=50),
        ),
    ]
