# Generated by Django 3.2.5 on 2021-09-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210909_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message_quantity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='notfication_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
