# Generated by Django 3.2.5 on 2021-09-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210909_0908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latname',
            new_name='lastname',
        ),
    ]
