# Generated by Django 3.2.5 on 2021-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='samKHa', max_length=50)),
                ('post_id', models.IntegerField(default=7)),
                ('react_type', models.CharField(default='Like', max_length=10)),
            ],
        ),
    ]
