# Generated by Django 3.2.5 on 2021-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('cover_image', models.FileField(default='media/defaultprof.png', upload_to='covers')),
                ('book_file', models.FileField(default='media/defaultprof.png', upload_to='books')),
            ],
        ),
    ]
