# Generated by Django 3.2.5 on 2021-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='samKHa', max_length=50)),
                ('post_id', models.CharField(default='1', max_length=50)),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('image1', models.ImageField(default='agrogator/pictures/product_pictures/default.jpeg', upload_to='agrogator/pictures/product_pictures')),
            ],
        ),
    ]
