# Generated by Django 3.2.5 on 2021-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image1',
            field=models.ImageField(default='media/defaultprof.png', upload_to='commentimgs'),
        ),
    ]
