# Generated by Django 3.2.5 on 2021-09-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
