# Generated by Django 3.2.5 on 2021-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('user_quantity', models.IntegerField(default=0)),
                ('gang_image', models.ImageField(default='agrogator/pictures/product_pictures/default.jpeg', upload_to='agrogator/pictures/product_pictures')),
            ],
        ),
    ]
