# Generated by Django 3.2.5 on 2021-09-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='gang_image',
            field=models.ImageField(default='front/src/gangimgs/defaultgang.png', upload_to='front/src/gangimgs'),
        ),
    ]
