# Generated by Django 3.2.5 on 2021-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gang', '0002_alter_gang_gang_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gang',
            name='gang_image',
            field=models.ImageField(default='media/defaultprof.png', upload_to='gangimgs'),
        ),
    ]
