# Generated by Django 3.2.5 on 2021-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gang',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
