# Generated by Django 3.2.5 on 2021-09-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_likes_post_reacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
    ]
